In [40]:
!pip install torch_optimizer
!pip install adabelief_pytorch==0.2.0

In [4]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

#Adam Optimizer
opt = torch.optim.Adam(model.parameters(), lr = 1e-3, betas= (0.9, 0.99))

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.]])
tensor([[103., 119.],
        [ 22.,  37.]])
Parameter containing:
tensor([[-0.2879,  0.0684,  0.3494],
        [-0.4197, -0.5304, -0.4759]], requires_grad=True)
Parameter containing:
tensor([ 0.2824, -0.2057], requires_grad=True)
Epoch [10/1000], Loss: 7098.9224
Epoch [20/1000], Loss: 36873.4609
Epoch [30/1000], Loss: 34213.8672
Epoch [40/1000], Loss: 5105.9722
Epoch [50/1000], Loss: 29536.7715
Epoch [60/1000], Loss: 16407.3145
Epoch [70/1000], Loss: 25352.6484
Epoch [80/1000], Loss: 13819.9072
Epoch [90/1000], Loss: 6423.6152
Epoch [100/1000], Loss: 5853.4258
Epoch [110/1000], Loss: 18396.1855
Epoch [120/1000], Loss: 12821.5547
Epoch [130/1000], Loss: 11820.9697
Epoch [140/1000], 

In [5]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.2711,  72.9354],
        [ 82.4718,  99.9207],
        [118.3351, 130.4749],
        [ 21.1113,  51.6273],
        [102.3900, 109.3802]], grad_fn=<AddmmBackward>)

In [6]:
model(torch.tensor([[75, 63, 44.]]))  #testing

tensor([[53.8207, 70.5284]], grad_fn=<AddmmBackward>)

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

# RMSprop Optimizer
opt = torch.optim.RMSprop(model.parameters(), lr = 1e-3, alpha = 0.9)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 81., 101.],
        [119., 133.]])
Parameter containing:
tensor([[ 0.2352, -0.5464,  0.0079],
        [-0.2062,  0.1731,  0.0788]], requires_grad=True)
Parameter containing:
tensor([ 0.0715, -0.3384], requires_grad=True)
Epoch [10/1000], Loss: 19636.9590
Epoch [20/1000], Loss: 12469.0762
Epoch [30/1000], Loss: 11149.3281
Epoch [40/1000], Loss: 350.1048
Epoch [50/1000], Loss: 236.5825
Epoch [60/1000], Loss: 1787.3027
Epoch [70/1000], Loss: 9540.7891
Epoch [80/1000], Loss: 5756.1968
Epoch [90/1000], Loss: 238.7309
Epoch [100/1000], Loss: 346.4984
Epoch [110/1000], Loss: 477.9740
Epoch [120/1000], Loss: 639.5429
Epoch [130/1000], Loss: 3738.6418
Epoch [140/1000], Loss: 355.46

In [2]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 62.5760,  70.2823],
        [ 86.1894,  99.6639],
        [104.2204, 134.7505],
        [ 49.8504,  37.3517],
        [ 91.8442, 117.1968]], grad_fn=<AddmmBackward>)

In [3]:
model(torch.tensor([[75, 63, 44.]]))  #testing

tensor([[61.4122, 67.1565]], grad_fn=<AddmmBackward>)

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

# SGD Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [ 56.,  70.]])
Parameter containing:
tensor([[ 0.2880, -0.3254, -0.0214],
        [ 0.2467, -0.2687,  0.4600]], requires_grad=True)
Parameter containing:
tensor([0.4249, 0.2777], requires_grad=True)
Epoch [10/1000], Loss: 2456.9268
Epoch [20/1000], Loss: 69.5563
Epoch [30/1000], Loss: 54.6558
Epoch [40/1000], Loss: 791.9073
Epoch [50/1000], Loss: 539.6657
Epoch [60/1000], Loss: 104.4114
Epoch [70/1000], Loss: 14.4393
Epoch [80/1000], Loss: 66.9806
Epoch [90/1000], Loss: 1.9617
Epoch [100/1000], Loss: 75.8572
Epoch [110/1000], Loss: 0.1052
Epoch [120/1000], Loss: 1.6111
Epoch [130/1000], Loss: 29.3748
Epoch [140/1000], Loss: 0.2482
Epoch [150/1000], Loss

In [2]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.2345,  70.3424],
        [ 82.0046, 100.5649],
        [118.9157, 133.0267],
        [ 21.1496,  37.0225],
        [101.6213, 119.0134]], grad_fn=<AddmmBackward>)

In [3]:
model(torch.tensor([[75, 63, 44.]]))  #testing

tensor([[53.6845, 67.4505]], grad_fn=<AddmmBackward>)

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch_optimizer as optim
from adabelief_pytorch import AdaBelief
import numpy as np


# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 2  # should be << number of observations
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break
    
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

# Define loss function
loss_fn = F.mse_loss

#Adabelief Optimizer
#opt = optim.AdaBelief(model.parameters(), lr=1e-3, betas=(0.9, 0.999), eps=1e-8)
opt = AdaBelief(model.parameters(), lr=1e-5, eps=1e-16, betas=(0.9, 0.999), print_change_log = False)

fit(1000, model, loss_fn, opt, train_dl)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[91., 88., 64.],
        [73., 67., 43.]])
tensor([[ 81., 101.],
        [ 56.,  70.]])
Parameter containing:
tensor([[ 0.5733,  0.1819, -0.4031],
        [-0.1938,  0.4370,  0.1081]], requires_grad=True)
Parameter containing:
tensor([0.5077, 0.1739], requires_grad=True)
Weight decoupling enabled in AdaBelief
Rectification enabled in AdaBelief
Epoch [10/1000], Loss: 358.8843
Epoch [20/1000], Loss: 980.1455
Epoch [30/1000], Loss: 1162.7297
Epoch [40/1000], Loss: 978.1852
Epoch [50/1000], Loss: 80.4590
Epoch [60/1000], Loss: 975.4134
Epoch [70/1000], Loss: 79.8270
Epoch [80/1000], Loss: 971.9753
Epoch [90/1000], Loss: 1165.1903
Epoch [100/1000], Loss: 1754.7004
Epoch [110/1000], Loss: 1166.3842
Epoch [120/1000], Loss: 964.0449
Epoch

In [2]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 59.0362,  63.2777],
        [ 71.8220,  84.9066],
        [ 87.1228, 115.3324],
        [ 71.7010,  46.2558],
        [ 58.1952,  91.0545]], grad_fn=<AddmmBackward>)

In [3]:
model(torch.tensor([[75, 63, 44.]]))  #testing

tensor([[58.6524, 60.8542]], grad_fn=<AddmmBackward>)